[package]
name = "weftext-agent-dsh"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
weftext-agent = { path = "../weftext-agent" }

[lints]
workspace = true
